[package]
name = "sand-castle-leptos"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bytemuck = "1.16"
leptos = "0.6"
leptos-use = "0.12"
sand-castle-core = { path = "../sand-castle-core" }
