[package]
name = "leptos-cube"
edition = '2021'

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7", features = ["csr"] }
sand-castle-leptos = { path = "../../crates/sand-castle-leptos" }
leptos-use = "0.15"
getrandom = { version = "0.3", features = ["wasm_js"] }
